# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import utils.basemodels


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(blank=True, help_text='resume/简历', null=True, upload_to=utils.basemodels.ModelHelper.upload_path, verbose_name='简历'),
        ),
    ]
