#!/bin/bash

# add this script to hooks
# give this file and executable permission

# Ignoring autogenerated files
#  -- Migration directories
# Ignoring error codes
#  -- E128 continuation line under-indented for visual indent
#  -- E402 module level import not at top of file
#  -- E501 line too long


echo '>> performing isort...'
isort -rc -sp . . -s venv

echo '>> checking pep8 code style...'
pycodestyle --exclude=migrations,venv --ignore=E128,E402,E501 .
