# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_userinfoimage_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoimage',
            name='resume',
            field=models.CharField(blank=True, help_text='简历', max_length=60, null=True, verbose_name='简历'),
        ),
    ]
