# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20180405_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccountinfo',
            name='password',
        ),
    ]
