# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_appconfiginfo_file_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiginfo',
            name='userinfo_field_names',
        ),
    ]
