# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_appconfiginfo_userinfo_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiginfo',
            name='userinfo_field_names',
            field=models.CharField(blank=True, help_text='用户需要填写的表单字段label名称', max_length=128, null=True, verbose_name='用户表单label'),
        ),
    ]
