# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20180328_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionqainfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '超时')], default=0, help_text='答题状态', verbose_name='答题状态'),
        ),
    ]
