# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20180404_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='account_id',
            field=models.CharField(blank=True, db_index=True, help_text='商家账户唯一标识', max_length=32, null=True, verbose_name='商家id'),
        ),
    ]
